# Import the existing retriever from the previous program
from retriever import retriever

# Import the tool decorator used to create an agent tool
from langchain_core.tools import tool

# Import the Gemini chat model
from langchain_google_genai import ChatGoogleGenerativeAI

# Import the Gemini configuration class
from shared.gemini_config import GeminiConfig

# Import create_agent to build an agent that can decide when to use a tool
from langchain.agents import create_agent


# Create a Gemini configuration object
# This loads the GEMINI_API_KEY from the .env file
gemini = GeminiConfig()


# Create the Gemini language model
# The agent will use this model for reasoning and answer generation
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=gemini.api_key
)


# Create a tool that allows the agent to search the HR policy
# The agent can decide to use this tool when the question requires document information
@tool
def search_hr_policy(query: str) -> str:
    """Search the company HR policy for relevant information."""

    # Retrieve the most relevant document chunks for the query
    relevant_chunks = retriever.invoke(query)

    # Convert the retrieved chunks into plain text
    return "\n\n".join(
        chunk.page_content for chunk in relevant_chunks
    )


# Give the agent access to the HR policy search tool
# The agent can decide when this tool is needed
agent = create_agent(
    model=llm,
    tools=[search_hr_policy],
    system_prompt="""
    You are an HR policy assistant.

    Use the search_hr_policy tool whenever the user asks
    about information that may be contained in the company HR policy.

    Answer only using information returned by the tool.
    If the required information is not found, say:
    "I could not find this information in the provided HR policy."
    """
)


# Ask the user to enter a question
# This makes the application interactive
question = input("\nEnter your question: ")


# Send the question to the agent
# The agent decides whether it needs to use the HR policy search tool
result = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }
)


# Get the final message generated by the agent
# The last message contains the agent's final response
answer = result["messages"][-1].content


# Extract the actual text from the structured response
# Gemini may return the content as a list containing text objects
if isinstance(answer, list):
    answer = "".join(
        item["text"]
        for item in answer
        if isinstance(item, dict) and item.get("type") == "text"
    )

# Display the final answer
print("\n--- Agent Answer ---")
print(answer)